# Generated by Django 5.2.7 on 2025-11-05 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunkers', '0003_add_locator_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(help_text='When do you plan to activate', verbose_name='Planned Date')),
                ('planned_time_start', models.TimeField(blank=True, help_text='Approximate start time in UTC', null=True, verbose_name='Start Time (UTC)')),
                ('planned_time_end', models.TimeField(blank=True, help_text='Approximate end time in UTC', null=True, verbose_name='End Time (UTC)')),
                ('callsign', models.CharField(help_text='Callsign that will be used during activation', max_length=20, verbose_name='Callsign')),
                ('bands', models.CharField(help_text='Which bands you plan to operate on (comma-separated)', max_length=200, verbose_name='Bands')),
                ('modes', models.CharField(help_text='Which modes you plan to use (comma-separated)', max_length=200, verbose_name='Modes')),
                ('comments', models.TextField(blank=True, help_text='Additional information about the activation', verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bunker', models.ForeignKey(help_text='Which bunker will be activated', on_delete=django.db.models.deletion.CASCADE, related_name='planned_activations', to='bunkers.bunker', verbose_name='Bunker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_activations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Planned Activation',
                'verbose_name_plural': 'Planned Activations',
                'ordering': ['planned_date', 'planned_time_start'],
                'indexes': [models.Index(fields=['planned_date'], name='planned_act_planned_4ffa46_idx'), models.Index(fields=['user'], name='planned_act_user_id_a4526b_idx'), models.Index(fields=['bunker'], name='planned_act_bunker__564d68_idx')],
            },
        ),
    ]
