# Generated by Django 5.2.7 on 2025-11-03 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique role name (e.g., Admin, Manager, Operator)', max_length=50, unique=True, verbose_name='role name')),
                ('description', models.TextField(blank=True, help_text='Description of the role and its permissions', verbose_name='description')),
                ('permissions', models.JSONField(default=dict, help_text='Custom permissions dictionary for this role', verbose_name='permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(db_index=True, help_text='Required. Email address used for authentication.', max_length=254, unique=True, verbose_name='email address')),
                ('callsign', models.CharField(db_index=True, help_text='Required. Unique callsign/display name.', max_length=50, unique=True, verbose_name='callsign')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active', verbose_name='active')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.userrole', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user role assignment',
                'verbose_name_plural': 'user role assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activator_qso', models.PositiveIntegerField(default=0, help_text='Total QSOs from bunkers as activator', verbose_name='total activator QSO')),
                ('unique_activations', models.PositiveIntegerField(default=0, help_text='Number of unique bunkers activated', verbose_name='unique activations')),
                ('activator_b2b_qso', models.PositiveIntegerField(default=0, help_text='Bunker-to-Bunker QSOs as activator', verbose_name='activator B2B QSO')),
                ('total_hunter_qso', models.PositiveIntegerField(default=0, help_text='Total hunted QSOs', verbose_name='total hunter QSO')),
                ('unique_bunkers_hunted', models.PositiveIntegerField(default=0, help_text='Number of unique bunkers hunted', verbose_name='unique bunkers hunted')),
                ('total_b2b_qso', models.PositiveIntegerField(default=0, help_text='Total Bunker-to-Bunker connections', verbose_name='total B2B QSO')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total points earned from all activities', verbose_name='total points')),
                ('hunter_points', models.PositiveIntegerField(default=0, help_text='Points earned from hunting activities', verbose_name='hunter points')),
                ('activator_points', models.PositiveIntegerField(default=0, help_text='Points earned from activating bunkers', verbose_name='activator points')),
                ('b2b_points', models.PositiveIntegerField(default=0, help_text='Points earned from B2B connections', verbose_name='B2B points')),
                ('event_points', models.PositiveIntegerField(default=0, help_text='Points earned from special events', verbose_name='event points')),
                ('diploma_points', models.PositiveIntegerField(default=0, help_text='Points earned from earning diplomas', verbose_name='diploma points')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user statistics',
                'verbose_name_plural': 'user statistics',
                'ordering': ['-total_points'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['callsign'], name='accounts_us_callsig_832880_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role')},
        ),
    ]
