# Generated by Django 5.2.7 on 2025-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='True if user was automatically created from log import, not manually registered.', verbose_name='auto created'),
        ),
    ]
