# Generated by Django 5.2.7 on 2025-11-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auto_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SQL Console',
                'verbose_name_plural': 'SQL Console',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='User must change password on next login', verbose_name='force password change'),
        ),
    ]
