# Generated by Django 5.2.7 on 2025-11-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sqlconsole_user_force_password_change'),
        ('activations', '0004_activationlog_activations_activat_92108a_idx_and_more'),
        ('bunkers', '0005_bunker_bunkers_bun_categor_a3586c_idx'),
        ('diplomas', '0007_add_layout_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='last_recalculated',
            field=models.DateTimeField(blank=True, help_text='When were statistics last recalculated from transactions', null=True, verbose_name='last recalculated'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='last_transaction_id',
            field=models.IntegerField(default=0, help_text='ID of last processed PointsTransaction', verbose_name='last transaction ID'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('activator_qso', 'Activator QSO'), ('hunter_qso', 'Hunter QSO'), ('b2b_confirmed', 'B2B Confirmed'), ('b2b_cancelled', 'B2B Cancelled'), ('diploma_bonus', 'Diploma Bonus'), ('event_bonus', 'Event Bonus'), ('manual_adjustment', 'Manual Adjustment'), ('reversal', 'Reversal')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('activator_points', models.IntegerField(default=0, verbose_name='Activator Points')),
                ('hunter_points', models.IntegerField(default=0, verbose_name='Hunter Points')),
                ('b2b_points', models.IntegerField(default=0, verbose_name='B2B Points')),
                ('event_points', models.IntegerField(default=0, verbose_name='Event Points')),
                ('diploma_points', models.IntegerField(default=0, verbose_name='Diploma Points')),
                ('reason', models.CharField(help_text='Short description of why points were awarded', max_length=255, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, help_text='Additional details or context', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('is_reversed', models.BooleanField(db_index=True, default=False, help_text='Has this transaction been reversed?', verbose_name='Is Reversed')),
                ('activation_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='activations.activationlog', verbose_name='Activation Log')),
                ('bunker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='bunkers.bunker', verbose_name='Bunker')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or system that created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='diplomas.diploma', verbose_name='Diploma')),
                ('reverses', models.ForeignKey(blank=True, help_text='If this is a reversal, which transaction does it reverse?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='accounts.pointstransaction', verbose_name='Reverses Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransactionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Batch Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False, verbose_name='Is Reversed')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reversed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('log_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_batch', to='activations.logupload', verbose_name='Log Upload')),
                ('transactions', models.ManyToManyField(related_name='batches', to='accounts.pointstransaction', verbose_name='Transactions')),
            ],
            options={
                'verbose_name': 'Points Transaction Batch',
                'verbose_name_plural': 'Points Transaction Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', '-created_at'], name='accounts_po_user_id_605bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='accounts_po_transac_7abd58_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='accounts_po_user_id_c3b603_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['activation_log'], name='accounts_po_activat_43b86c_idx'),
        ),
    ]
