# Generated by Django 5.2.7 on 2025-11-04 18:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunkers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique activation key (auto-generated)', max_length=20, unique=True, verbose_name='Activation Key')),
                ('valid_from', models.DateTimeField(help_text='When does this key become valid?', verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When does this key expire? (leave blank for permanent)', null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, help_text='Can this key be used?', verbose_name='Active')),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this key can be used (blank = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Uses')),
                ('times_used', models.IntegerField(default=0, help_text='How many times has this key been used?', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Times Used')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this key', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User who can use this key (blank = anyone can use)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_keys', to='bunkers.bunker', verbose_name='Bunker')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Activation Key',
                'verbose_name_plural': 'Activation Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(help_text='When did the activation occur?', verbose_name='Activation Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When did the activation end?', null=True, verbose_name='End Date')),
                ('qso_count', models.IntegerField(default=0, help_text='Number of contacts made during this activation', validators=[django.core.validators.MinValueValidator(0)], verbose_name='QSO Count')),
                ('is_b2b', models.BooleanField(default=False, help_text='Was this a B2B activation?', verbose_name='Bunker-to-Bunker (B2B)')),
                ('notes', models.TextField(blank=True, help_text='Notes about this activation', verbose_name='Notes')),
                ('verified', models.BooleanField(default=False, help_text='Has this activation been verified?', verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_key', models.ForeignKey(blank=True, help_text='Key used for this activation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_logs', to='activations.activationkey', verbose_name='Activation Key')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='bunkers.bunker', verbose_name='Bunker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_activations', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Activation Log',
                'verbose_name_plural': 'Activation Logs',
                'ordering': ['-activation_date'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Unique license or permit number', max_length=50, unique=True, verbose_name='License Number')),
                ('license_type', models.CharField(choices=[('contest', 'Contest License'), ('special_event', 'Special Event'), ('temporary', 'Temporary Permit'), ('training', 'Training License'), ('other', 'Other')], default='other', max_length=20, verbose_name='License Type')),
                ('title_pl', models.CharField(max_length=200, verbose_name='Title (Polish)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_pl', models.TextField(blank=True, verbose_name='Description (Polish)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, help_text='Is this license currently active?', verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunkers', models.ManyToManyField(blank=True, help_text='Bunkers covered by this license (leave blank for all)', related_name='licenses', to='bunkers.bunker', verbose_name='Authorized Bunkers')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Issued To')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddIndex(
            model_name='activationkey',
            index=models.Index(fields=['key'], name='activations_key_e9c20d_idx'),
        ),
        migrations.AddIndex(
            model_name='activationkey',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='activations_is_acti_f14b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['user', 'activation_date'], name='activations_user_id_fd7de7_idx'),
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['bunker', 'activation_date'], name='activations_bunker__49b4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['verified'], name='activations_verifie_199a26_idx'),
        ),
    ]
