# Generated by Django 5.2.7 on 2025-11-04 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activationlog',
            name='activator',
            field=models.ForeignKey(blank=True, help_text='User who was activating the bunker', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activator_logs', to=settings.AUTH_USER_MODEL, verbose_name='Activator'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='band',
            field=models.CharField(blank=True, default='', help_text='Radio band (e.g., 80m, 40m, 2m)', max_length=20, verbose_name='Band'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='mode',
            field=models.CharField(blank=True, default='', help_text='Radio mode (e.g., SSB, CW, FM, FT8)', max_length=20, verbose_name='Mode'),
        ),
    ]
