# Generated by Django 5.2.7 on 2025-11-05 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activations', '0002_activationlog_activator_activationlog_band_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename of the uploaded log', max_length=255, verbose_name='Filename')),
                ('file_format', models.CharField(help_text='Format of the log file (ADIF, CSV, etc.)', max_length=20, verbose_name='File Format')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('qso_count', models.IntegerField(default=0, help_text='Number of QSOs in this upload', verbose_name='QSO Count')),
                ('processed_qso_count', models.IntegerField(default=0, help_text='Number of QSOs successfully processed', verbose_name='Processed QSO Count')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text='Error details if upload failed', verbose_name='Error Message')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_uploads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log Upload',
                'verbose_name_plural': 'Log Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='activationlog',
            name='log_upload',
            field=models.ForeignKey(blank=True, help_text='The upload batch this QSO belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qsos', to='activations.logupload', verbose_name='Log Upload'),
        ),
        migrations.AddIndex(
            model_name='logupload',
            index=models.Index(fields=['user', '-uploaded_at'], name='activations_user_id_462fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='logupload',
            index=models.Index(fields=['status'], name='activations_status_ed9d7b_idx'),
        ),
    ]
