# Generated by Django 5.2.7 on 2025-11-06 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activations', '0003_logupload_activationlog_log_upload_and_more'),
        ('bunkers', '0005_bunker_bunkers_bun_categor_a3586c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['activator', 'activation_date'], name='activations_activat_92108a_idx'),
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['is_b2b', 'verified'], name='activations_is_b2b_e67a0f_idx'),
        ),
    ]
