# Generated by Django 5.2.7 on 2025-11-07 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_points_transaction_system'),
        ('activations', '0004_activationlog_activations_activat_92108a_idx_and_more'),
        ('bunkers', '0005_bunker_bunkers_bun_categor_a3586c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activationlog',
            name='b2b_confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='Has reciprocal B2B QSO been uploaded and confirmed?', verbose_name='B2B Confirmed'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='b2b_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When was the B2B confirmed?', null=True, verbose_name='B2B Confirmed At'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='b2b_partner',
            field=models.ForeignKey(blank=True, help_text='The other operator in this B2B contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_partnerships', to=settings.AUTH_USER_MODEL, verbose_name='B2B Partner'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='b2b_partner_log',
            field=models.ForeignKey(blank=True, help_text="Link to the partner's matching log entry", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciprocal_b2b', to='activations.activationlog', verbose_name='Reciprocal B2B Log'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='points_awarded',
            field=models.BooleanField(db_index=True, default=False, help_text='Have points been awarded for this QSO?', verbose_name='Points Awarded'),
        ),
        migrations.AddField(
            model_name='activationlog',
            name='points_transaction',
            field=models.ForeignKey(blank=True, help_text='Link to the points transaction for this QSO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_logs_link', to='accounts.pointstransaction', verbose_name='Points Transaction'),
        ),
        migrations.AddField(
            model_name='logupload',
            name='file_checksum',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64, null=True, verbose_name='File Checksum (SHA256)'),
        ),
        migrations.AlterUniqueTogether(
            name='activationlog',
            unique_together={('activator', 'user', 'bunker', 'activation_date')},
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['points_awarded'], name='activations_points__2a704e_idx'),
        ),
        migrations.AddIndex(
            model_name='activationlog',
            index=models.Index(fields=['b2b_confirmed'], name='activations_b2b_con_28cd3d_idx'),
        ),
    ]
