# Generated by Django 5.2.7 on 2025-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activations', '0005_add_points_transaction_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationlog',
            name='activator_callsign',
            field=models.CharField(blank=True, help_text='Full callsign used during activation (e.g., SP3FCK/P, DL/SP3FCK)', max_length=50, verbose_name='Activator Callsign'),
        ),
    ]
