# Generated by Django 5.2.7 on 2025-11-03 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(help_text='Category name in Polish', max_length=100, verbose_name='Name (Polish)')),
                ('name_en', models.CharField(help_text='Category name in English', max_length=100, verbose_name='Name (English)')),
                ('description_pl', models.TextField(blank=True, help_text='Category description in Polish', verbose_name='Description (Polish)')),
                ('description_en', models.TextField(blank=True, help_text='Category description in English', verbose_name='Description (English)')),
                ('icon', models.CharField(blank=True, help_text="Icon class or name for the category (e.g., 'fas fa-shield-alt')", max_length=50, verbose_name='Icon')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories are displayed', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bunker Category',
                'verbose_name_plural': 'Bunker Categories',
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text="Unique reference code for the bunker (e.g., 'BNK-001')", max_length=50, unique=True, verbose_name='Reference Number')),
                ('name_pl', models.CharField(help_text='Bunker name in Polish', max_length=200, verbose_name='Name (Polish)')),
                ('name_en', models.CharField(help_text='Bunker name in English', max_length=200, verbose_name='Name (English)')),
                ('description_pl', models.TextField(blank=True, help_text='Detailed description in Polish', verbose_name='Description (Polish)')),
                ('description_en', models.TextField(blank=True, help_text='Detailed description in English', verbose_name='Description (English)')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude coordinate (-90 to 90)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude coordinate (-180 to 180)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this bunker been verified by an administrator?', verbose_name='Verified')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bunkers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bunkers', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bunkers', to='bunkers.bunkercategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Bunker',
                'verbose_name_plural': 'Bunkers',
                'ordering': ['reference_number'],
            },
        ),
        migrations.CreateModel(
            name='BunkerInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(help_text='When did the inspection/visit occur?', verbose_name='Inspection Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the inspection', verbose_name='Notes')),
                ('verified', models.BooleanField(default=False, help_text='Has this inspection been verified?', verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='bunkers.bunker', verbose_name='Bunker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunker_inspections', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bunker Inspection',
                'verbose_name_plural': 'Bunker Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='BunkerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='bunker_photos/%Y/%m/', verbose_name='Photo')),
                ('caption_pl', models.CharField(blank=True, max_length=200, verbose_name='Caption (Polish)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Caption (English)')),
                ('is_approved', models.BooleanField(default=False, help_text='Has this photo been approved by a moderator?', verbose_name='Approved')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_photos', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bunkers.bunker', verbose_name='Bunker')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Bunker Photo',
                'verbose_name_plural': 'Bunker Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BunkerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pl', models.CharField(max_length=200, verbose_name='Title (Polish)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('url', models.URLField(help_text='External link to resource', verbose_name='URL')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('map', 'Map'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=50, verbose_name='Resource Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_resources', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='bunkers.bunker', verbose_name='Bunker')),
            ],
            options={
                'verbose_name': 'Bunker Resource',
                'verbose_name_plural': 'Bunker Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bunker',
            index=models.Index(fields=['reference_number'], name='bunkers_bun_referen_998eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='bunker',
            index=models.Index(fields=['is_verified'], name='bunkers_bun_is_veri_d2403c_idx'),
        ),
        migrations.AddIndex(
            model_name='bunker',
            index=models.Index(fields=['latitude', 'longitude'], name='bunkers_bun_latitud_dd7c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bunkerinspection',
            unique_together={('bunker', 'user', 'inspection_date')},
        ),
    ]
