# Generated by Django 5.2.7 on 2025-11-05 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0002_bunkerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='locator',
            field=models.CharField(blank=True, help_text='Maidenhead grid locator (e.g., JO72RI)', max_length=10, verbose_name='Locator'),
        ),
        migrations.AlterField(
            model_name='bunkerrequest',
            name='bunker',
            field=models.ForeignKey(blank=True, help_text='The bunker created from this request if approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_request', to='bunkers.bunker', verbose_name='Created Bunker'),
        ),
        migrations.AddIndex(
            model_name='bunkerrequest',
            index=models.Index(fields=['status', '-created_at'], name='bunkers_bun_status_3b59a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bunkerrequest',
            index=models.Index(fields=['requested_by'], name='bunkers_bun_request_83e73f_idx'),
        ),
    ]
