# Generated by Django 5.2.7 on 2025-11-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0003_add_locator_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunkerrequest',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference code will be assigned automatically upon approval', max_length=50, null=True, verbose_name='Reference Number'),
        ),
    ]
