# Generated by Django 5.2.7 on 2025-11-06 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0004_alter_bunkerrequest_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bunker',
            index=models.Index(fields=['category', 'is_verified'], name='bunkers_bun_categor_a3586c_idx'),
        ),
    ]
