# Generated by Django 5.2.7 on 2025-12-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0005_bunker_bunkers_bun_categor_a3586c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name_pl', models.CharField(blank=True, help_text='Leave empty if no change needed', max_length=200, null=True, verbose_name='New Name (Polish)')),
                ('new_name_en', models.CharField(blank=True, help_text='Leave empty if no change needed', max_length=200, null=True, verbose_name='New Name (English)')),
                ('new_description_pl', models.TextField(blank=True, help_text='Leave empty if no change needed', null=True, verbose_name='New Description (Polish)')),
                ('new_description_en', models.TextField(blank=True, help_text='Leave empty if no change needed', null=True, verbose_name='New Description (English)')),
                ('new_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Leave empty if no change needed', max_digits=9, null=True, verbose_name='New Latitude')),
                ('new_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Leave empty if no change needed', max_digits=9, null=True, verbose_name='New Longitude')),
                ('correction_reason', models.TextField(help_text='Explain why this correction is needed', verbose_name='Correction Reason')),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information or evidence', verbose_name='Additional Info')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('bunker', models.ForeignKey(help_text='The bunker to be corrected', on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='bunkers.bunker', verbose_name='Bunker')),
                ('new_category', models.ForeignKey(blank=True, help_text='Leave empty if no change needed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bunkers.bunkercategory', verbose_name='New Category')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunker_correction_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bunker_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Bunker Correction Request',
                'verbose_name_plural': 'Bunker Correction Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bunkers_bun_status_19e13e_idx'), models.Index(fields=['bunker'], name='bunkers_bun_bunker__10b35a_idx'), models.Index(fields=['requested_by'], name='bunkers_bun_request_770079_idx')],
            },
        ),
    ]
