# Generated by Django 5.2.7 on 2026-01-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0006_add_bunker_correction_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunkerrequest',
            name='info_url',
            field=models.URLField(blank=True, help_text='Link to external information about the bunker (optional)', verbose_name='Information URL'),
        ),
    ]
