# Generated by Django 5.2.7 on 2026-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0007_bunkerrequest_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='info_url',
            field=models.URLField(blank=True, help_text='External URL with additional information about the bunker', max_length=500, verbose_name='Info URL'),
        ),
    ]
