# Generated by Django 5.2.7 on 2025-11-04 18:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunkers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(help_text='Cluster name in Polish', max_length=200, verbose_name='Name (Polish)')),
                ('name_en', models.CharField(help_text='Cluster name in English', max_length=200, verbose_name='Name (English)')),
                ('description_pl', models.TextField(blank=True, help_text='Detailed description in Polish', verbose_name='Description (Polish)')),
                ('description_en', models.TextField(blank=True, help_text='Detailed description in English', verbose_name='Description (English)')),
                ('region', models.CharField(blank=True, help_text="Geographic region (e.g., 'Pomorskie', 'Mazowieckie')", max_length=100, verbose_name='Region')),
                ('is_active', models.BooleanField(default=True, help_text='Is this cluster currently active?', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clusters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['region', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ClusterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pl', models.CharField(max_length=200, verbose_name='Title (Polish)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('message_pl', models.TextField(verbose_name='Message (Polish)')),
                ('message_en', models.TextField(verbose_name='Message (English)')),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('event', 'Event'), ('warning', 'Warning'), ('special', 'Special Activation')], default='info', max_length=20, verbose_name='Alert Type')),
                ('is_active', models.BooleanField(default=True, help_text='Should this alert be displayed?', verbose_name='Active')),
                ('start_date', models.DateTimeField(help_text='When should this alert start being displayed?', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When should this alert stop being displayed? (leave blank for no end)', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cluster.cluster', verbose_name='Cluster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Cluster Alert',
                'verbose_name_plural': 'Cluster Alerts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True, help_text='When was this bunker added to the cluster?', verbose_name='Join Date')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which bunkers are displayed within the cluster', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this bunker's role in the cluster", verbose_name='Notes')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_cluster_members', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='bunkers.bunker', verbose_name='Bunker')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cluster.cluster', verbose_name='Cluster')),
            ],
            options={
                'verbose_name': 'Cluster Member',
                'verbose_name_plural': 'Cluster Members',
                'ordering': ['cluster', 'display_order', 'bunker__reference_number'],
                'unique_together': {('cluster', 'bunker')},
            },
        ),
    ]
