# Generated by Django 5.2.7 on 2025-11-05 15:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkers', '0003_add_locator_field'),
        ('cluster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activator_callsign', models.CharField(help_text='Callsign of the operator activating the bunker', max_length=20, verbose_name='Activator Callsign')),
                ('frequency', models.DecimalField(decimal_places=3, help_text='Operating frequency in MHz (e.g., 14.230)', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('1.8')), django.core.validators.MaxValueValidator(Decimal('450.0'))], verbose_name='Frequency (MHz)')),
                ('band', models.CharField(blank=True, help_text='Amateur radio band (auto-detected from frequency)', max_length=10, verbose_name='Band')),
                ('bunker_reference', models.CharField(blank=True, help_text='Bunker reference number (e.g., B/SP-0039) - optional', max_length=20, verbose_name='Bunker Reference')),
                ('comment', models.CharField(blank=True, help_text="Optional comment (e.g., '73!', 'QRV SSB')", max_length=200, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this spot was refreshed', verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(help_text='When this spot will expire (30 minutes from last update)', verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, help_text='Is this spot still active?', verbose_name='Active')),
                ('bunker', models.ForeignKey(blank=True, help_text='Resolved bunker object (if reference provided)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spots', to='bunkers.bunker', verbose_name='Bunker')),
                ('spotter', models.ForeignKey(help_text='User who posted this spot', on_delete=django.db.models.deletion.CASCADE, related_name='posted_spots', to=settings.AUTH_USER_MODEL, verbose_name='Spotter')),
            ],
            options={
                'verbose_name': 'Spot',
                'verbose_name_plural': 'Spots',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['activator_callsign', 'frequency', 'is_active'], name='cluster_spo_activat_d755d1_idx'), models.Index(fields=['expires_at', 'is_active'], name='cluster_spo_expires_d33503_idx'), models.Index(fields=['-updated_at'], name='cluster_spo_updated_55cdd1_idx'), models.Index(fields=['band', 'is_active'], name='cluster_spo_band_e37a2d_idx')],
            },
        ),
    ]
