# Generated by Django 5.2.7 on 2025-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='bunker_reference',
            field=models.CharField(blank=True, help_text='Bunker reference number (e.g., B/SP-0039) - optional', max_length=20, null=True, verbose_name='Bunker Reference'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='comment',
            field=models.CharField(blank=True, default='', help_text="Optional comment (e.g., '73!', 'QRV SSB')", max_length=200, null=True, verbose_name='Comment'),
        ),
    ]
