# Generated by Django 5.2.7 on 2025-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_alter_spot_bunker_reference_alter_spot_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='respot_count',
            field=models.IntegerField(default=0, help_text='Number of times this spot has been re-spotted', verbose_name='Respot Count'),
        ),
    ]
