# Generated by Django 5.2.7 on 2025-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_spot_respot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='last_respot_time',
            field=models.DateTimeField(blank=True, help_text='Time of the most recent respot', null=True, verbose_name='Last Respot Time'),
        ),
    ]
