# Generated by Django 5.2.7 on 2025-11-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_spot_last_respot_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respotted_at', models.DateTimeField(auto_now_add=True, verbose_name='Respotted At')),
                ('comment', models.CharField(blank=True, help_text='Optional comment for this respot', max_length=200, null=True, verbose_name='Comment')),
                ('respotter', models.ForeignKey(help_text='User who made this respot', on_delete=django.db.models.deletion.CASCADE, related_name='respots', to=settings.AUTH_USER_MODEL, verbose_name='Respotter')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respot_history', to='cluster.spot', verbose_name='Spot')),
            ],
            options={
                'verbose_name': 'Spot History',
                'verbose_name_plural': 'Spot History',
                'ordering': ['-respotted_at'],
            },
        ),
    ]
