# Generated by Django 5.2.7 on 2025-11-06 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_spothistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spothistory',
            index=models.Index(fields=['spot', '-respotted_at'], name='cluster_spo_spot_id_2ca6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='spothistory',
            index=models.Index(fields=['respotter', '-respotted_at'], name='cluster_spo_respott_aa2df3_idx'),
        ),
    ]
