# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, verbose_name='Name (Polish)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('description_pl', models.TextField(verbose_name='Description (Polish)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('category', models.CharField(choices=[('hunter', 'Hunter'), ('activator', 'Activator'), ('b2b', 'Bunker-to-Bunker'), ('special_event', 'Special Event'), ('cluster', 'Cluster Achievement'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('requirements', models.JSONField(default=dict, help_text="JSON structure defining requirements (e.g., {'min_bunkers': 10, 'min_qsos': 50})", verbose_name='Requirements')),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded when diploma is earned', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Awarded')),
                ('template_image', models.ImageField(blank=True, help_text='Background template for PDF generation', upload_to='diploma_templates/', verbose_name='Template Image')),
                ('is_active', models.BooleanField(default=True, help_text='Can this diploma be earned?', verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diploma Type',
                'verbose_name_plural': 'Diploma Types',
                'ordering': ['category', 'display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Issue Date')),
                ('diploma_number', models.CharField(help_text='Unique diploma certificate number', max_length=50, unique=True, verbose_name='Diploma Number')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for verifying diploma authenticity', unique=True, verbose_name='Verification Code')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='diplomas/%Y/%m/', verbose_name='PDF File')),
                ('requirements_met', models.JSONField(default=dict, help_text='Snapshot of requirements at time of issuance', verbose_name='Requirements Met')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Admin who issued/approved the diploma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_diplomas', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('diploma_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomas', to='diplomas.diplomatype', verbose_name='Diploma Type')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Verified At')),
                ('verified_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address of verifier', null=True, verbose_name='Verified By IP')),
                ('verification_method', models.CharField(choices=[('number', 'Diploma Number'), ('code', 'Verification Code'), ('qr', 'QR Code Scan'), ('manual', 'Manual Check')], default='number', max_length=50, verbose_name='Verification Method')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='diplomas.diploma', verbose_name='Diploma')),
                ('verified_by_user', models.ForeignKey(blank=True, help_text='User who performed verification (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diploma_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verified By User')),
            ],
            options={
                'verbose_name': 'Diploma Verification',
                'verbose_name_plural': 'Diploma Verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='DiplomaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.JSONField(default=dict, help_text='Current values for tracked requirements', verbose_name='Current Progress')),
                ('percentage_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentage Complete')),
                ('is_eligible', models.BooleanField(default=False, help_text='Has user met all requirements?', verbose_name='Eligible')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('diploma_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='diplomas.diplomatype', verbose_name='Diploma Type')),
            ],
            options={
                'verbose_name': 'Diploma Progress',
                'verbose_name_plural': 'Diploma Progress Records',
                'ordering': ['-percentage_complete'],
                'unique_together': {('user', 'diploma_type')},
            },
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['user', 'issue_date'], name='diplomas_di_user_id_fbbd92_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['diploma_number'], name='diplomas_di_diploma_ef1d79_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['verification_code'], name='diplomas_di_verific_6042a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diploma',
            unique_together={('diploma_type', 'user')},
        ),
    ]
