# Generated by Django 5.2.7 on 2025-11-04 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='requirements_met',
        ),
        migrations.RemoveField(
            model_name='diplomaprogress',
            name='current_progress',
        ),
        migrations.RemoveField(
            model_name='diplomatype',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='diplomatype',
            name='requirements',
        ),
        migrations.AddField(
            model_name='diploma',
            name='activator_points_earned',
            field=models.IntegerField(default=0, verbose_name='Activator Points at Issuance'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='b2b_points_earned',
            field=models.IntegerField(default=0, verbose_name='B2B Points at Issuance'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='hunter_points_earned',
            field=models.IntegerField(default=0, verbose_name='Hunter Points at Issuance'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='activator_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Activator Points'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='b2b_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='B2B Points'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='hunter_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hunter Points'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_activator_points',
            field=models.IntegerField(default=0, help_text='Each QSO as activator = 1 point', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Activator Points'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_b2b_points',
            field=models.IntegerField(default=0, help_text='Each bunker-to-bunker QSO = 1 point', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum B2B Points'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_hunter_points',
            field=models.IntegerField(default=0, help_text='Each hunted QSO = 1 point', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Hunter Points'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Start date for time-limited diploma (leave empty for permanent)', null=True, verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='valid_to',
            field=models.DateField(blank=True, help_text='End date for time-limited diploma (leave empty for permanent)', null=True, verbose_name='Valid To'),
        ),
    ]
