# Generated by Django 5.2.7 on 2025-11-05 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0002_remove_diploma_requirements_met_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatype',
            name='min_total_activations',
            field=models.IntegerField(default=0, help_text='Total number of bunker activations (can repeat same bunker)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Total Activations'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_total_hunted',
            field=models.IntegerField(default=0, help_text='Total number of bunkers hunted (can repeat same bunker)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Total Hunted'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_unique_activations',
            field=models.IntegerField(default=0, help_text='Number of different bunkers activated', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Unique Bunkers Activated'),
        ),
        migrations.AddField(
            model_name='diplomatype',
            name='min_unique_hunted',
            field=models.IntegerField(default=0, help_text='Number of different bunkers hunted', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Unique Bunkers Hunted'),
        ),
    ]
