# Generated by Django 5.2.7 on 2025-11-05 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0003_add_bunker_count_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomaprogress',
            name='total_activations',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Activations'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='total_hunted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Hunted'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='unique_activations',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unique Bunkers Activated'),
        ),
        migrations.AddField(
            model_name='diplomaprogress',
            name='unique_hunted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unique Bunkers Hunted'),
        ),
    ]
