# Generated by Django 5.2.7 on 2025-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0004_add_progress_bunker_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatype',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for element positions: {callsign_x: 14.5, callsign_y: 10, ...}', verbose_name='Layout Configuration'),
        ),
    ]
