# Generated by Django 5.2.7 on 2025-11-06 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0005_add_layout_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomatype',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text="Advanced PDF layout configuration. Structure: {'callsign': {'enabled': true, 'x': 14.5, 'y': 10, 'font': 'Lato', 'size': 24, 'bold': true, 'italic': false, 'color': '#000000'}, ...} Available elements: callsign, diploma_name, date, points, diploma_number, qr_code", verbose_name='Layout Configuration'),
        ),
        migrations.CreateModel(
            name='FontFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this font (e.g., 'Arial', 'Times New Roman')", max_length=100, verbose_name='Font Name')),
                ('font_file', models.FileField(help_text='Upload TTF or OTF font file', upload_to='diploma_fonts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ttf', 'otf'])], verbose_name='Font File')),
                ('font_type', models.CharField(choices=[('regular', 'Regular'), ('bold', 'Bold'), ('italic', 'Italic'), ('bold_italic', 'Bold Italic')], default='regular', help_text='Specify if this is regular, bold, italic, or bold-italic variant', max_length=20, verbose_name='Font Type')),
                ('is_active', models.BooleanField(default=True, help_text='Only active fonts appear in diploma configuration', verbose_name='Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Font File',
                'verbose_name_plural': 'Font Files',
                'ordering': ['name', 'font_type'],
                'unique_together': {('name', 'font_type')},
            },
        ),
    ]
