# Generated by Django 5.2.7 on 2025-11-06 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0006_add_font_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaLayoutElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('callsign', 'Callsign'), ('diploma_name', 'Diploma Name'), ('date', 'Issue Date'), ('points', 'Points Information'), ('diploma_number', 'Diploma Number'), ('qr_code', 'QR Code')], max_length=20, verbose_name='Element Type')),
                ('enabled', models.BooleanField(default=True, help_text='Show this element on the diploma', verbose_name='Enabled')),
                ('x_position', models.DecimalField(decimal_places=2, default=14.5, help_text='Horizontal position from left edge (center alignment)', max_digits=5, verbose_name='X Position (cm)')),
                ('y_position', models.DecimalField(decimal_places=2, default=10.0, help_text='Vertical position from bottom edge', max_digits=5, verbose_name='Y Position (cm)')),
                ('font_family', models.CharField(default='Lato', help_text='Font name (e.g., Lato, Arial, Times)', max_length=100, verbose_name='Font Family')),
                ('font_size', models.IntegerField(default=24, help_text='Font size in points (minimum 6)', validators=[django.core.validators.MinValueValidator(6)], verbose_name='Font Size')),
                ('bold', models.BooleanField(default=False, verbose_name='Bold')),
                ('italic', models.BooleanField(default=False, verbose_name='Italic')),
                ('color', models.CharField(default='#333333', help_text='Text color in hex format (e.g., #333333)', max_length=7, verbose_name='Color')),
                ('qr_size', models.DecimalField(blank=True, decimal_places=2, default=3.0, help_text='Only for QR code element', max_digits=5, null=True, verbose_name='QR Code Size (cm)')),
                ('diploma_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_elements', to='diplomas.diplomatype', verbose_name='Diploma Type')),
            ],
            options={
                'verbose_name': 'Layout Element',
                'verbose_name_plural': 'Layout Elements',
                'ordering': ['element_type'],
                'unique_together': {('diploma_type', 'element_type')},
            },
        ),
    ]
